import { mkdir, open } from "node:fs/promises"
import { dirname, join } from "node:path"
import { gzipSync, gunzipSync } from "node:zlib"

const API = "https://api.vercel.com", AUTH = "I_UNDERSTAND_THIS_CREATES_AND_DELETES_VERCEL_SANDBOX_RESOURCES", MAX = 1_048_576, LOG_MAX = 65_536, PAGES = 100
type Fetcher = (input: string | URL | Request, init?: RequestInit) => Promise<Response>
export interface VercelProbeConfig { token: string; teamId: string; projectId: string; artifactDirectory: string; pollIntervalMs: number; pollTimeoutMs: number; requestTimeoutMs: number }
export interface VercelProbeDependencies { fetch: Fetcher; now(): number; sleep(ms: number, signal: AbortSignal): Promise<void>; randomId(): string; output(path: string, contents: string): Promise<void> }
type Sandbox = { name: string; sessionId: string; cwd: string; status: string; tags: Record<string, string> }
type Snapshot = { id: string; sourceSessionId: string; status: string }
type Operation = { path: string; method: string; mutation: boolean; status?: number; mediaType?: string; shape?: string; facts?: Record<string, boolean | number | string> }

export function loadVercelProbeConfig(env: Record<string, string | undefined>, argv: readonly string[], underBunTest = bunTest()): VercelProbeConfig {
  if (underBunTest) throw new Error("Live Vercel Sandbox capability probe is disabled under bun test")
  if (!argv.includes("--run")) throw new Error("Live Vercel Sandbox capability probe requires literal --run")
  if (env.VERCEL_SANDBOX_CAPABILITY_PROBE_AUTHORIZATION !== AUTH || env.VERCEL_SANDBOX_CAPABILITY_PROBE_ISOLATED_PROJECT !== "YES") throw new Error("Live Vercel Sandbox capability probe lacks required authorization")
  for (const key of ["VERCEL_TOKEN", "VERCEL_TEAM_ID", "VERCEL_PROJECT_ID"] as const) if (!plain(env[key])) throw new Error(`${key} is required`)
  return { token: env.VERCEL_TOKEN!, teamId: env.VERCEL_TEAM_ID!, projectId: env.VERCEL_PROJECT_ID!, artifactDirectory: env.VERCEL_SANDBOX_PROBE_ARTIFACT_DIRECTORY ?? ".waterbox/probes", pollIntervalMs: positive(env.VERCEL_SANDBOX_PROBE_POLL_INTERVAL_MS, 1000), pollTimeoutMs: positive(env.VERCEL_SANDBOX_PROBE_POLL_TIMEOUT_MS, 120000), requestTimeoutMs: positive(env.VERCEL_SANDBOX_PROBE_REQUEST_TIMEOUT_MS, 30000) }
}

export function buildGzipTar(path: string, contents: Uint8Array, mode = 0o640): Uint8Array {
  const name = path.slice(1), bytes = new TextEncoder().encode(name)
  if (!path.startsWith("/") || !name || /\\|\/\/|(^|\/)\.{1,2}(\/|$)/.test(name) || bytes.byteLength !== name.length || bytes.byteLength > 100 || contents.byteLength > MAX || !Number.isInteger(mode) || mode < 0 || mode > 0o7777) throw new Error("invalid probe archive input")
  const header = new Uint8Array(512); header.set(bytes); octal(header, 100, 8, mode); octal(header, 108, 8, 0); octal(header, 116, 8, 0); octal(header, 124, 12, contents.byteLength); octal(header, 136, 12, 0); header.fill(32, 148, 156); header[156] = 48; header.set(new TextEncoder().encode("ustar\0"), 257); header.set(new TextEncoder().encode("00"), 263); octal(header, 148, 8, sum(header))
  const padding = (512 - contents.byteLength % 512) % 512, tar = new Uint8Array(512 + contents.byteLength + padding + 1024); tar.set(header); tar.set(contents, 512); return gzipSync(tar)
}
export function inspectGzipTar(bytes: Uint8Array): { path: string; mode: number; contents: Uint8Array; checksumValid: boolean } { const tar = gunzipSync(bytes), h = tar.subarray(0, 512), nameEnd = h.indexOf(0), size = parseOctal(h.subarray(124, 136)), stored = parseOctal(h.subarray(148, 156)), copy = new Uint8Array(h); copy.fill(32, 148, 156); return { path: new TextDecoder("utf-8", { fatal: true }).decode(h.subarray(0, nameEnd)), mode: parseOctal(h.subarray(100, 108)), contents: tar.slice(512, 512 + size), checksumValid: stored === sum(copy) } }

export async function runVercelSandboxCapabilityProbe(config: VercelProbeConfig, deps: VercelProbeDependencies): Promise<void> {
  const operations: Operation[] = [], api = new Client(config, deps, operations), run = `waterbox-v6-${safeId(deps.randomId())}`, tags = { "waterbox-probe": run }, owned = new Map<string, Sandbox>(), snapshots = new Map<string, Snapshot>(), sessions = new Set<string>()
  let baseline: { sandboxes: Set<string>; snapshots: Set<string> } | undefined, failure: unknown, cleanupErrors: unknown[] = [], exact = false
  try {
    baseline = { sandboxes: new Set((await api.listSandboxes()).map(x => x.name)), snapshots: new Set((await api.listSnapshots()).filter(activeSnapshot).map(x => x.id)) }
    const source = await api.create(`${run}-source`, tags); own(source)
    await api.inspect(source.name, false, tags)
    await api.runNode(source.sessionId)
    await api.runPwd(source.sessionId)
    await api.runChecked(source.sessionId, "rg-present", "set -eu; command -v rg >/dev/null", "", source.cwd)
    await api.runChecked(source.sessionId, "privilege", "set -eu; if test \"$(id -u)\" = 0; then install -d -m 755 -o \"$(id -u)\" -g \"$(id -g)\" /workspace; printf 'root\\n'; else command -v sudo >/dev/null; sudo -n install -d -m 755 -o \"$(id -u)\" -g \"$(id -g)\" /workspace; printf 'sudo\\n'; fi", undefined, source.cwd)
    await api.write(source.sessionId, buildGzipTar("/tmp/waterbox-probe.txt", new TextEncoder().encode("marker\n")))
    await api.runChecked(source.sessionId, "upload", "set -eu; test \"$(cat /tmp/waterbox-probe.txt)\" = marker; test \"$(stat -c %a /tmp/waterbox-probe.txt)\" = 640", "", "/workspace")
    trackStop(await api.stop(source.sessionId))
    await discoverSnapshots()
    const resumed = await api.inspect(source.name, true, tags); if (resumed.sessionId === source.sessionId) throw new Error("resume did not establish a session"); own(resumed)
    await api.runChecked(resumed.sessionId, "resume-persistence", "set -eu; test -f /tmp/waterbox-probe.txt", "", "/workspace")
    const manual = await api.snapshot(resumed.sessionId); snapshots.set(manual.snapshot.id, manual.snapshot)
    const inspected = await api.afterSnapshot(source.name, tags)
    api.fact("manual-snapshot", { responseStatus: manual.responseStatus, namedSandboxStatus: inspected.status, sourceStopped: inspected.status === "stopped" }); await discoverSnapshots()
    const afterSnapshot = inspected.status === "stopped" ? await api.inspect(source.name, true, tags) : inspected
    if (inspected.status === "stopped" && afterSnapshot.sessionId === inspected.sessionId) throw new Error("resume did not establish a session")
    own(afterSnapshot)
    const derived = await api.create(`${run}-derived`, tags, manual.snapshot.id); own(derived)
    await api.runChecked(derived.sessionId, "snapshot-restore", "set -eu; test -f /tmp/waterbox-probe.txt", "", "/workspace")
    const long = await api.command(derived.sessionId, "/bin/sh", ["-c", "set -eu; sleep 30"], 45_000, "/workspace"); await api.running(derived.sessionId, long); await api.kill(derived.sessionId, long); const killed = await api.wait(derived.sessionId, long, false); if (killed.stderr || killed.error) throw new Error("killed command reported runner failure"); api.fact("command-kill", { nonzeroExit: true })
  } catch (error) { failure = error }
  cleanupErrors.push(...await cleanup())
  try { exact = !!baseline && equal(baseline.sandboxes, new Set((await api.listSandboxes()).map(x => x.name))) && equal(baseline.snapshots, new Set((await api.listSnapshots()).filter(activeSnapshot).map(x => x.id))) } catch (error) { cleanupErrors.push(error) }
  const outcome = !failure && !cleanupErrors.length && exact ? "passed" : "failed", common = { schemaVersion: 2, outcome, baselineCaptured: !!baseline, cleanup: { exactBaseline: exact, errors: cleanupErrors.length }, operations: operations.map(sanitizeOperation) }
  // Raw data is only an emergency cleanup ledger. It never contains credentials, request bodies, commands, or response errors.
  await Promise.all([deps.output(join(config.artifactDirectory, `${run}.raw.json`), JSON.stringify({ ...common, owned: { sandboxes: [...owned.keys()], snapshots: [...snapshots.keys()], sessions: [...sessions] } })), deps.output(join(config.artifactDirectory, `${run}.sanitized.json`), JSON.stringify(common))])
  if (failure || cleanupErrors.length || !exact) throw new Error("Vercel Sandbox probe failed; inspect the sanitized artifact")

  function own(value: Sandbox) { owned.set(value.name, value); sessions.add(value.sessionId) }
  function trackStop(value: { sessionId: string; snapshot?: Snapshot }) { sessions.add(value.sessionId); if (value.snapshot) snapshots.set(value.snapshot.id, value.snapshot) }
  async function discoverSnapshots() { if (!baseline) return; for (const item of await api.listSnapshots()) if (activeSnapshot(item) && !baseline.snapshots.has(item.id) && sessions.has(item.sourceSessionId)) snapshots.set(item.id, item) }
  async function cleanup() {
    const errors: unknown[] = []; if (!baseline) return errors
    try { await discoverSnapshots() } catch (error) { errors.push(error) }
    for (const sandbox of [...owned.values()].reverse()) {
      let current: Sandbox | undefined
      try { current = await api.inspectOptional(sandbox.name, sandbox.tags) } catch (error) { errors.push(error); continue }
      if (!current) continue
      sessions.add(current.sessionId)
      if (current.status === "running") try { trackStop(await api.stop(current.sessionId)) } catch (error) { errors.push(error) }
      // Deletion also stops a running sandbox, so do not let a rejected stop leak it.
      try { await api.deleteSandbox(current) } catch (error) { errors.push(error) }
      try { await discoverSnapshots() } catch (error) { errors.push(error) }
    }
    try { await discoverSnapshots() } catch (error) { errors.push(error) }
    for (const snapshot of snapshots.values()) if (sessions.has(snapshot.sourceSessionId)) try { snapshots.set(snapshot.id, await api.deleteSnapshot(snapshot.id)) } catch (error) { errors.push(error) }
    try { await api.absentAll([...owned.keys()], [...snapshots.keys()]) } catch (error) { errors.push(error) }
    return errors
  }
}

class Client {
  constructor(private readonly c: VercelProbeConfig, private readonly d: VercelProbeDependencies, private readonly evidence: Operation[]) {}
  async listSandboxes() { return this.pages("sandboxes", sandboxList) }
  async listSnapshots() { return this.pages("snapshots", snapshotList) }
  async pages<T>(kind: "sandboxes" | "snapshots", parse: (x: unknown) => T[]): Promise<T[]> { const out: T[] = []; let cursor: string | undefined; for (let page = 0; page < PAGES; page++) { const value = await this.json("GET", kind === "sandboxes" ? "/v2/sandboxes" : "/v2/sandboxes/snapshots", undefined, { project: this.c.projectId, teamId: this.c.teamId, limit: "50", ...(cursor ? { cursor } : {}) }); if (!object(value) || !object(value.pagination) || !Number.isSafeInteger(value.pagination.count) || (value.pagination.next !== null && !plain(value.pagination.next))) throw new Error("invalid pagination response"); out.push(...parse(value)); if (value.pagination.next === null) return out; cursor = value.pagination.next } throw new Error("pagination safety bound exceeded") }
  async create(name: string, tags: Record<string, string>, snapshotId?: string) { try { return envelope(await this.json("POST", "/v4/sandboxes", { name, projectId: this.c.projectId, tags, persistent: true, ...(snapshotId ? { source: { type: "snapshot", snapshotId } } : {}) }, { teamId: this.c.teamId }, true), name, this.c.projectId, tags) } catch (error) { if (!transport(error)) throw error; try { return await this.inspect(name, false, tags) } catch { throw new Error("ambiguous sandbox create could not be safely reconciled") } } }
  async inspect(name: string, resume: boolean, tags: Record<string, string>) { return envelope(await this.json("GET", `/v2/sandboxes/${segment(name)}`, undefined, { projectId: this.c.projectId, teamId: this.c.teamId, resume: String(resume) }, resume), name, this.c.projectId, tags) }
  async inspectOptional(name: string, tags: Record<string, string>) { try { return await this.inspect(name, false, tags) } catch (error) { if (error instanceof Http && error.status === 404) return undefined; throw error } }
  async afterSnapshot(name: string, tags: Record<string, string>) { const deadline = this.d.now() + this.c.pollTimeoutMs; while (true) { const current = await this.inspect(name, false, tags); if (["running", "stopped"].includes(current.status)) return current; if (["failed", "aborted"].includes(current.status)) throw new Error("snapshot left sandbox failed"); if (!["pending", "snapshotting", "stopping"].includes(current.status)) throw new Error("snapshot returned unknown sandbox status"); if (this.d.now() >= deadline) throw new Error("snapshot state polling timed out"); await this.d.sleep(this.c.pollIntervalMs, AbortSignal.timeout(this.c.requestTimeoutMs)) } }
  async write(session: string, body: Uint8Array) { await this.json("POST", `/v2/sandboxes/sessions/${segment(session)}/fs/write`, body, { teamId: this.c.teamId }, true, "application/gzip", { "x-cwd": "/" }) }
  async command(session: string, commandName: string, args: string[], timeout: number, cwd?: string) { return command(await this.json("POST", `/v2/sandboxes/sessions/${segment(session)}/cmd`, { command: commandName, args, ...(cwd ? { cwd } : {}), env: {}, sudo: false, timeout }, { teamId: this.c.teamId }, true), session).id }
  async runNode(session: string) { const id = await this.command(session, "node", ["--version"], 30_000), result = await this.wait(session, id, true); if (result.stderr || result.error || !/^v24\.\d+\.\d+\n$/.test(result.stdout)) throw new Error("checked command failed: node-version"); this.fact("node-version", { passed: true, stdoutBytes: result.stdout.length }) }
  async runPwd(session: string) { const id = await this.command(session, "/bin/sh", ["-c", "set -eu; pwd"], 30_000), result = await this.wait(session, id, true); if (result.stderr || result.error || !normalizedAbsolutePath(result.stdout.slice(0, -1)) || !result.stdout.endsWith("\n")) throw new Error("checked command failed: default-cwd"); this.fact("default-cwd", { absolute: true }) }
  async runChecked(session: string, label: string, script: string, expected?: string, cwd?: string) { const id = await this.command(session, "/bin/sh", ["-c", script], 30_000, cwd), result = await this.wait(session, id, true); if (result.stderr || result.error || (expected !== undefined && result.stdout !== expected) || (expected === undefined && !["root\n", "sudo\n"].includes(result.stdout))) throw new Error(`checked command failed: ${label}`); this.fact(label, { passed: true, stdoutBytes: result.stdout.length }) }
  async running(session: string, id: string) { const value = command(await this.json("GET", `/v2/sandboxes/sessions/${segment(session)}/cmd/${segment(id)}`, undefined, { teamId: this.c.teamId }), session); if (value.exitCode !== null) throw new Error("long command ended before kill") }
  async wait(session: string, id: string, expectZero: boolean): Promise<{ stdout: string; stderr: string; error: string; exitCode: number }> { const deadline = this.d.now() + this.c.pollTimeoutMs; while (true) { let current: { id: string; exitCode: number | null }; try { current = command(await this.json("GET", `/v2/sandboxes/sessions/${segment(session)}/cmd/${segment(id)}`, undefined, { teamId: this.c.teamId, wait: "true" }), session) } catch (error) { if (!transport(error) || this.d.now() >= deadline) throw error; await this.d.sleep(this.c.pollIntervalMs, AbortSignal.timeout(this.c.requestTimeoutMs)); continue } if (current.id !== id) throw new Error("command identity mismatch"); if (current.exitCode !== null) { const logs = await this.logs(session, id); if ((expectZero && current.exitCode !== 0) || (!expectZero && current.exitCode === 0)) throw new Error("unexpected command exit code"); return { ...logs, exitCode: current.exitCode } } if (this.d.now() >= deadline) throw new Error("command polling timed out"); await this.d.sleep(this.c.pollIntervalMs, AbortSignal.timeout(this.c.requestTimeoutMs)) } }
  async logs(session: string, id: string) { const response = await this.request("GET", `/v2/sandboxes/sessions/${segment(session)}/cmd/${segment(id)}/logs`, undefined, { teamId: this.c.teamId }); this.record("GET", "/v2/sandboxes/sessions/{sessionId}/cmd/{commandId}/logs", false, response); if (!response.ok) throw new Http(response.status); if (media(response) !== "application/x-ndjson") throw new Error("invalid command logs response"); const text = await bounded(response, LOG_MAX, AbortSignal.timeout(this.c.requestTimeoutMs)); const result = { stdout: "", stderr: "", error: "" }; for (const line of text.split("\n")) { if (!line) continue; let item: unknown; try { item = JSON.parse(line) } catch { throw new Error("malformed command logs") } if (!object(item) || !["stdout", "stderr", "error"].includes(String(item.stream))) throw new Error("malformed command logs"); if (item.stream === "error") { if (!object(item.data) || typeof item.data.code !== "string" || typeof item.data.message !== "string") throw new Error("malformed command logs"); result.error = "error"; continue } if (typeof item.data !== "string") throw new Error("malformed command logs"); const stream = item.stream as "stdout" | "stderr"; if (result.stdout.length + result.stderr.length + item.data.length > LOG_MAX) throw new Error("command logs exceed size limit"); result[stream] += item.data } return result }
  async kill(session: string, id: string) { const value = command(await this.json("POST", `/v2/sandboxes/sessions/${segment(session)}/cmd/${segment(id)}/kill`, { signal: 15 }, { teamId: this.c.teamId }, true), session); if (value.id !== id) throw new Error("kill command identity mismatch") }
  async stop(session: string) { const value = await this.json("POST", `/v2/sandboxes/sessions/${segment(session)}/stop`, undefined, { teamId: this.c.teamId }, true); if (!object(value) || !object(value.session) || value.session.id !== session || value.session.status !== "stopped") throw new Error("invalid stop response"); return { sessionId: session, ...(object(value.snapshot) ? { snapshot: snapshot(value.snapshot, session) } : {}) } }
  async snapshot(session: string) { const value = await this.json("POST", `/v3/sandboxes/sessions/${segment(session)}/snapshot`, {}, { teamId: this.c.teamId }, true); if (!object(value) || !object(value.session) || value.session.id !== session || !sessionStatus(value.session.status) || !object(value.snapshot)) throw new Error("invalid snapshot response"); return { snapshot: snapshot(value.snapshot, session), responseStatus: value.session.status } }
  async deleteSandbox(sandbox: Sandbox) { try { await this.json("DELETE", `/v2/sandboxes/${segment(sandbox.name)}`, undefined, { projectId: this.c.projectId, teamId: this.c.teamId, deleteOrphanSnapshots: "false" }, true) } catch (error) { if (!(error instanceof Http && error.status === 404)) throw error } await this.absent(`/v2/sandboxes/${segment(sandbox.name)}`, { projectId: this.c.projectId, teamId: this.c.teamId }) }
  async deleteSnapshot(id: string) { const current = await this.inspectSnapshot(id); if (!current) return { id, sourceSessionId: "", status: "deleted" }; if (current.id !== id) throw new Error("snapshot identity mismatch"); if (current.status === "deleted") return current; let deleted: Snapshot | undefined; try { const value = await this.json("DELETE", `/v2/sandboxes/snapshots/${segment(id)}`, undefined, { teamId: this.c.teamId }, true); if (!object(value) || !object(value.snapshot)) throw new Error("invalid snapshot delete response"); deleted = snapshot(value.snapshot); if (deleted.id !== id || deleted.status !== "deleted") throw new Error("snapshot delete was not terminal") } catch (error) { if (error instanceof Http && [400, 409].includes(error.status)) { const reconciled = await this.inspectSnapshot(id); if (reconciled?.id === id && reconciled.status === "deleted") return reconciled } else if (error instanceof Http && error.status === 404) return { id, sourceSessionId: "", status: "deleted" }; throw error } return await this.absentSnapshot(id, deleted) }
  async inspectSnapshot(id: string) { try { const response = await this.json("GET", `/v2/sandboxes/snapshots/${segment(id)}`, undefined, { teamId: this.c.teamId }); return snapshot(object(response) && object(response.snapshot) ? response.snapshot : response) } catch (error) { if (error instanceof Http && error.status === 404) return undefined; throw error } }
  async absentAll(names: string[], ids: string[]) { for (const name of names) await this.absent(`/v2/sandboxes/${segment(name)}`, { projectId: this.c.projectId, teamId: this.c.teamId }); for (const id of ids) await this.absentSnapshot(id) }
  async absent(path: string, query: Record<string, string>) { const deadline = this.d.now() + this.c.pollTimeoutMs; while (true) { try { await this.json("GET", path, undefined, query) } catch (error) { if (error instanceof Http && error.status === 404) return; throw error } if (this.d.now() >= deadline) throw new Error("deleted resource remained present"); await this.d.sleep(this.c.pollIntervalMs, AbortSignal.timeout(this.c.requestTimeoutMs)) } }
  async absentSnapshot(id: string, deleted?: Snapshot) { const deadline = this.d.now() + this.c.pollTimeoutMs; while (true) { try { const response = await this.json("GET", `/v2/sandboxes/snapshots/${segment(id)}`, undefined, { teamId: this.c.teamId }), value = snapshot(object(response) && object(response.snapshot) ? response.snapshot : response); if (value.id === id && value.status === "deleted") return value; throw new Error("deleted snapshot remained active") } catch (error) { if (error instanceof Http && error.status === 404) return deleted ?? { id, sourceSessionId: "", status: "deleted" }; throw error } if (this.d.now() >= deadline) throw new Error("deleted snapshot remained present"); await this.d.sleep(this.c.pollIntervalMs, AbortSignal.timeout(this.c.requestTimeoutMs)) } }
  async json(method: string, path: string, body?: unknown, query: Record<string, string> = {}, mutation = false, contentType = "application/json", headers: Record<string, string> = {}) { const response = await this.request(method, path, body, query, contentType, headers); this.record(method, template(path), mutation, response); if (!response.ok) { cancel(response.body); throw new Http(response.status) } if (media(response) !== "application/json") { cancel(response.body); throw new Error("invalid response media type") } const value = JSON.parse(await bounded(response, MAX, AbortSignal.timeout(this.c.requestTimeoutMs))); this.evidence.at(-1)!.shape = shape(value); return value }
  request(method: string, path: string, body?: unknown, query: Record<string, string> = {}, contentType = "application/json", headers: Record<string, string> = {}) { const url = new URL(path, API); for (const [key, value] of Object.entries(query)) url.searchParams.set(key, value); const binary = body instanceof Uint8Array; return this.d.fetch(url, { method, headers: { authorization: `Bearer ${this.c.token}`, accept: "application/json", "content-type": binary ? contentType : "application/json", ...headers }, body: binary ? new Uint8Array(body).buffer : body === undefined ? undefined : JSON.stringify(body), signal: AbortSignal.timeout(this.c.requestTimeoutMs) }) }
  record(method: string, path: string, mutation: boolean, response: Response) { this.evidence.push({ method, path, mutation, status: response.status, mediaType: media(response) }) }
  fact(label: string, facts: Record<string, boolean | number | string>) { this.evidence.push({ method: "CHECK", path: label, mutation: false, facts }) }
}

function envelope(value: unknown, name: string, project: string, tags: Record<string, string>): Sandbox { if (!object(value) || !object(value.sandbox) || !object(value.session) || value.sandbox.name !== name || value.sandbox.currentSessionId !== value.session.id || value.session.projectId !== project || !object(value.sandbox.tags) || Object.entries(tags).some(([k, v]) => value.sandbox.tags[k] !== v) || !plain(value.session.id) || !normalizedAbsolutePath(value.session.cwd) || !sandboxStatus(value.sandbox.status)) throw new Error("invalid sandbox response"); return { name, sessionId: value.session.id, cwd: value.session.cwd, status: value.sandbox.status, tags } }
function sandboxList(value: unknown): Sandbox[] { if (!object(value) || !Array.isArray(value.sandboxes)) throw new Error("invalid sandbox list"); return value.sandboxes.map(x => { if (!object(x) || !plain(x.name) || !object(x.tags)) throw new Error("invalid sandbox list identity"); return { name: x.name, sessionId: plain(x.currentSessionId) ? x.currentSessionId : "", cwd: "", status: String(x.status), tags: x.tags as Record<string, string> } }) }
function snapshotList(value: unknown): Snapshot[] { if (!object(value) || !Array.isArray(value.snapshots)) throw new Error("invalid snapshot list"); return value.snapshots.map(x => snapshot(x)) }
function snapshot(value: unknown, source?: string): Snapshot { if (!object(value) || !plain(value.id) || !plain(value.sourceSessionId) || !["created", "deleted", "failed"].includes(String(value.status)) || (source && value.sourceSessionId !== source)) throw new Error("invalid snapshot response"); return { id: value.id, sourceSessionId: value.sourceSessionId, status: value.status } }
function sessionStatus(value: unknown): value is "pending" | "snapshotting" | "running" | "stopping" | "stopped" | "failed" | "aborted" { return ["pending", "snapshotting", "running", "stopping", "stopped", "failed", "aborted"].includes(String(value)) }
function sandboxStatus(value: unknown): value is "pending" | "snapshotting" | "running" | "stopping" | "stopped" | "failed" | "aborted" { return sessionStatus(value) }
function activeSnapshot(value: Snapshot) { return value.status !== "deleted" }
function command(value: unknown, session: string) { if (!object(value) || !object(value.command) || !plain(value.command.id) || value.command.sessionId !== session || (value.command.exitCode !== null && !Number.isInteger(value.command.exitCode))) throw new Error("invalid command response"); return { id: value.command.id, exitCode: value.command.exitCode as number | null } }
function sanitizeOperation(operation: Operation) { return { ...operation, ...(operation.facts ? { facts: operation.facts } : {}) } }
function template(path: string) { return path.replace(/\/sandboxes\/sessions\/[^/]+/g, "/sandboxes/sessions/{sessionId}").replace(/\/cmd\/[^/]+/g, "/cmd/{commandId}").replace(/\/sandboxes\/snapshots\/[^/]+/g, "/sandboxes/snapshots/{snapshotId}").replace(/\/sandboxes\/(?!sessions(?:\/|$)|snapshots(?:\/|$))[^/]+/g, "/sandboxes/{name}") }
function shape(value: unknown) { return object(value) ? Object.keys(value).sort().filter(key => /^[a-zA-Z][a-zA-Z0-9]*$/.test(key)).slice(0, 12).join(",") : Array.isArray(value) ? "array" : typeof value }
function media(response: Response) { return response.headers.get("content-type")?.split(";", 1)[0] ?? "" }
function octal(out: Uint8Array, start: number, length: number, value: number) { out.set(new TextEncoder().encode(value.toString(8).padStart(length - 1, "0") + "\0"), start) }
function parseOctal(bytes: Uint8Array) { const text = new TextDecoder().decode(bytes).replace(/\0.*$/, "").trim(); return text ? Number.parseInt(text, 8) : 0 }
function sum(bytes: Uint8Array) { return bytes.reduce((total, byte) => total + byte, 0) }
function object(value: unknown): value is Record<string, any> { return typeof value === "object" && value !== null && !Array.isArray(value) }
function plain(value: unknown): value is string { return typeof value === "string" && value.length > 0 && value === value.trim() }
function normalizedAbsolutePath(value: unknown): value is string { return plain(value) && value.length <= 1024 && value.startsWith("/") && !/[\\\0-\x1f\x7f]|\/\/|(?:^|\/)\.{1,2}(?:\/|$)/.test(value) }
function safeId(value: string) { const id = value.toLowerCase().replace(/[^a-z0-9]/g, "").slice(0, 20); if (id.length < 8) throw new Error("invalid random identifier"); return id }
function segment(value: string) { return encodeURIComponent(value) }
function positive(value: string | undefined, fallback: number) { const n = value === undefined ? fallback : Number(value); if (!Number.isSafeInteger(n) || n <= 0) throw new Error("probe timing configuration is invalid"); return n }
function equal(a: Set<string>, b: Set<string>) { return a.size === b.size && [...a].every(x => b.has(x)) }
function transport(error: unknown) { return error instanceof TypeError || error instanceof DOMException && ["AbortError", "TimeoutError"].includes(error.name) }
function cancel(body: ReadableStream<Uint8Array> | null) { if (body) void body.cancel().catch(() => undefined) }
class Http extends Error { constructor(readonly status: number) { super(`Vercel API request failed (${status})`) } }
async function bounded(response: Response, limit: number, signal: AbortSignal) { if (!response.body) throw new Error("empty response"); const reader = response.body.getReader(), chunks: Uint8Array[] = []; let size = 0, done = false; const abort = () => { void reader.cancel(signal.reason).catch(() => undefined) }; signal.addEventListener("abort", abort, { once: true }); try { while (true) { const item = await readAbortable(reader, signal); if (item.done) { done = true; break } if ((size += item.value.byteLength) > limit) throw new Error("response exceeds size limit"); chunks.push(item.value) } } finally { signal.removeEventListener("abort", abort); if (!done) await reader.cancel().catch(() => undefined); reader.releaseLock() } const bytes = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength } return new TextDecoder("utf-8", { fatal: true }).decode(bytes) }
function readAbortable(reader: ReadableStreamDefaultReader<Uint8Array>, signal: AbortSignal): Promise<Awaited<ReturnType<ReadableStreamDefaultReader<Uint8Array>["read"]>>> { return new Promise((resolve, reject) => { const fail = () => { clean(); reject(signal.reason ?? new DOMException("Aborted", "AbortError")) }, clean = () => signal.removeEventListener("abort", fail); signal.addEventListener("abort", fail, { once: true }); if (signal.aborted) return fail(); reader.read().then(x => { clean(); resolve(x) }, x => { clean(); reject(x) }) }) }
async function output(path: string, text: string) { await mkdir(dirname(path), { recursive: true, mode: 0o700 }); const file = await open(path, "w", 0o600); try { await file.writeFile(text); await file.chmod(0o600) } finally { await file.close() } }
function bunTest() { return process.argv.includes("test") && process.argv.some(x => /(?:^|\/)bun(?:$|\s)/.test(x)) }
export async function main() { const config = loadVercelProbeConfig(process.env, process.argv.slice(2)); await runVercelSandboxCapabilityProbe(config, { fetch, now: Date.now, sleep: async (ms, signal) => { signal.throwIfAborted(); await Bun.sleep(ms); signal.throwIfAborted() }, randomId: () => crypto.randomUUID(), output }); console.log(`Vercel Sandbox capability probe passed; sanitized artifact written under ${config.artifactDirectory}`) }
if (import.meta.main) await main().catch(() => { console.error("Vercel Sandbox capability probe failed; inspect the sanitized artifact"); process.exitCode = 1 })
