import { describe, expect, test } from "bun:test"
import { buildGzipTar, inspectGzipTar, loadVercelProbeConfig, runVercelSandboxCapabilityProbe, type VercelProbeConfig } from "./vercel-sandbox-capability-probe.ts"

const config: VercelProbeConfig = { token: "token-secret", teamId: "team-private", projectId: "project-private", artifactDirectory: "/private", pollIntervalMs: 1, pollTimeoutMs: 100, requestTimeoutMs: 1000 }
const run = "waterbox-v6-0123456789abcdef", source = `${run}-source`, derived = `${run}-derived`, s1 = "session-source", s2 = "session-resume", s3 = "session-after-snapshot", s4 = "session-derived", manual = "snapshot-manual", baselineSandbox = "baseline-sandbox", baselineSnapshot = "baseline-snapshot"

describe("Vercel Sandbox capability probe", () => {
  test("requires authorization and validates portable ustar input", () => {
    expect(() => loadVercelProbeConfig({ VERCEL_TOKEN: "secret" }, ["--run"], true)).toThrow("disabled under bun test")
    const authorized = { VERCEL_TOKEN: "x", VERCEL_TEAM_ID: "t", VERCEL_PROJECT_ID: "p", VERCEL_SANDBOX_CAPABILITY_PROBE_AUTHORIZATION: "I_UNDERSTAND_THIS_CREATES_AND_DELETES_VERCEL_SANDBOX_RESOURCES", VERCEL_SANDBOX_CAPABILITY_PROBE_ISOLATED_PROJECT: "YES" }
    expect(() => loadVercelProbeConfig(authorized, [], false)).toThrow("literal --run")
    expect(() => loadVercelProbeConfig({ ...authorized, VERCEL_SANDBOX_CAPABILITY_PROBE_AUTHORIZATION: "wrong" }, ["--run"], false)).toThrow("lacks required authorization")
    expect(() => loadVercelProbeConfig({ ...authorized, VERCEL_SANDBOX_CAPABILITY_PROBE_ISOLATED_PROJECT: "NO" }, ["--run"], false)).toThrow("lacks required authorization")
    expect(loadVercelProbeConfig(authorized, ["--run"], false).token).toBe("x")
    const result = inspectGzipTar(buildGzipTar("/tmp/probe.txt", new TextEncoder().encode("hello"))); expect(result.path).toBe("tmp/probe.txt"); expect(result.mode).toBe(0o640); expect(result.checksumValid).toBe(true)
    for (const path of ["relative", "/a//b", "/a/../b", "/a\\b", `/caf${String.fromCharCode(233)}`]) expect(() => buildGzipTar(path, new Uint8Array())).toThrow("invalid probe archive input")
  })
  test("runs full fake-server lifecycle with exact REST contracts, pagination, cleanup, and redacted artifacts", async () => {
    const server = fakeServer(), artifacts = new Map<string, string>(); await runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async (p, v) => { artifacts.set(p, v) } })
    expect(server.requests.some(x => x.method === "GET" && x.path === "/v2/sandboxes" && x.query.includes("project=project-private") && x.query.includes("teamId=team-private") && x.query.includes("limit=50"))).toBe(true)
    expect(server.requests.some(x => x.method === "GET" && x.path === "/v2/sandboxes" && x.query.includes("cursor=next-page"))).toBe(true)
    const snapshotPost = server.requests.findIndex(x => x.method === "POST" && x.path === `/v3/sandboxes/sessions/${s2}/snapshot`), inspected = server.requests.findIndex((x, index) => index > snapshotPost && x.method === "GET" && x.path === `/v2/sandboxes/${source}` && x.query.includes("resume=false")); expect(snapshotPost).toBeGreaterThan(-1); expect(inspected).toBeGreaterThan(snapshotPost); expect(server.requests.slice(snapshotPost + 1).some(x => x.method === "GET" && x.path === `/v2/sandboxes/${source}` && x.query.includes("resume=true"))).toBe(false)
    expect(server.requests.filter(x => x.method === "POST" && x.path === "/v4/sandboxes").map(x => x.body)).toEqual([{ name: source, projectId: config.projectId, tags: { "waterbox-probe": run }, persistent: true }, { name: derived, projectId: config.projectId, tags: { "waterbox-probe": run }, persistent: true, source: { type: "snapshot", snapshotId: manual } }])
    expect(server.requests.find(x => x.path.endsWith("/fs/write"))!.contentType).toBe("application/gzip"); expect(server.requests.find(x => x.path.endsWith("/fs/write"))!.cwd).toBe("/"); expect(server.requests.filter(x => !x.path.endsWith("/fs/write")).every(x => x.contentType === "application/json")).toBe(true); expect(server.requests.find(x => x.path.endsWith("/stop"))!.contentType).toBe("application/json"); expect(server.requests.find(x => x.path.endsWith("/cmd/cmd-long/kill"))!.body).toEqual({ signal: 15 })
    const commands = server.requests.filter(x => x.method === "POST" && x.path.endsWith("/cmd")); expect(commands[0]!.body).toEqual({ command: "node", args: ["--version"], env: {}, sudo: false, timeout: 30_000 }); expect(commands[1]!.body).toEqual({ command: "/bin/sh", args: ["-c", "set -eu; pwd"], env: {}, sudo: false, timeout: 30_000 }); expect(commands.slice(2, 4).every(x => (x.body as { cwd?: string }).cwd === "/home/probe-default")).toBe(true); expect(commands.slice(4).every(x => (x.body as { cwd?: string }).cwd === "/workspace")).toBe(true)
    expect(server.requests.filter(x => x.method === "DELETE" && x.path.startsWith("/v2/sandboxes/") && !x.path.includes("snapshots")).every(x => x.query.includes("deleteOrphanSnapshots=false"))).toBe(true)
    const commandReads = server.requests.filter(x => x.method === "GET" && /\/cmd\/[^/]+$/.test(x.path)), kill = server.requests.findIndex(x => x.method === "POST" && x.path.endsWith("/cmd/cmd-long/kill")), normalReads = commandReads.filter(x => !x.path.endsWith("/cmd-long")), runningRead = commandReads.find(x => x.path.endsWith("/cmd-long") && server.requests.indexOf(x) < kill), killedReads = commandReads.filter(x => x.path.endsWith("/cmd-long") && server.requests.indexOf(x) > kill)
    expect(normalReads.length).toBeGreaterThan(0); expect(normalReads.every(x => x.query === "teamId=team-private&wait=true")).toBe(true)
    expect(runningRead?.query).toBe("teamId=team-private")
    expect(killedReads.length).toBeGreaterThan(0); expect(killedReads.every(x => x.query === "teamId=team-private&wait=true")).toBe(true)
    expect(server.requests.filter(x => x.method !== "GET").some(x => x.path.includes(baselineSandbox) || x.path.includes(baselineSnapshot))).toBe(false)
    const sanitized = [...artifacts.entries()].find(([p]) => p.endsWith("sanitized.json"))![1]!, raw = [...artifacts.entries()].find(([p]) => p.endsWith("raw.json"))![1]!, evidence = JSON.parse(sanitized).operations as Array<{ method: string; path: string; mutation: boolean; facts?: Record<string, unknown> }>, snapshotFact = evidence.find(x => x.path === "manual-snapshot")!.facts!; for (const value of [config.token, config.teamId, config.projectId, source, derived, s1, manual, baselineSandbox, baselineSnapshot, "sleep 30"]) expect(sanitized).not.toContain(value); for (const value of ["/home/probe-default", "/workspace", "sleep 30"]) { expect(sanitized).not.toContain(value); expect(raw).not.toContain(value) } expect(sanitized).toContain("exactBaseline\":true"); expect(sanitized).toContain('"default-cwd"'); expect(sanitized).toContain('"absolute":true'); expect(snapshotFact).toEqual({ responseStatus: "running", namedSandboxStatus: "running", sourceStopped: false }); expect(JSON.stringify(snapshotFact)).not.toMatch(/id|cwd/i); expect(evidence.some(x => x.method === "GET" && x.path === "/v2/sandboxes/{name}" && x.mutation)).toBe(true); for (const path of ["/v2/sandboxes/sessions/{sessionId}/cmd", "/v2/sandboxes/sessions/{sessionId}/stop", "/v2/sandboxes/snapshots"]) expect(evidence.some(x => x.path === path)).toBe(true)
  })
  test("explicitly resumes only when a manual snapshot leaves the named sandbox stopped", async () => {
    const server = fakeServer({ manualSnapshotStops: true }), artifacts = new Map<string, string>(); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async (p, v) => { artifacts.set(p, v) } })).resolves.toBeUndefined()
    const snapshotPost = server.requests.findIndex(x => x.method === "POST" && x.path.endsWith("/snapshot")), resume = server.requests.findIndex((x, index) => index > snapshotPost && x.method === "GET" && x.path === `/v2/sandboxes/${source}` && x.query.includes("resume=true")); expect(resume).toBeGreaterThan(snapshotPost)
    const evidence = JSON.parse([...artifacts.entries()].find(([p]) => p.endsWith("sanitized.json"))![1]!).operations as Array<{ path: string; facts?: Record<string, unknown> }>; expect(evidence.find(x => x.path === "manual-snapshot")!.facts).toEqual({ responseStatus: "running", namedSandboxStatus: "stopped", sourceStopped: true })
  })
  test("non-mutatingly polls snapshotting sandbox status until it runs", async () => {
    const server = fakeServer({ snapshottingReads: 2, snapshotResponseStatus: "snapshotting" }); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async () => {} })).resolves.toBeUndefined()
    const snapshotPost = server.requests.findIndex(x => x.method === "POST" && x.path.endsWith("/snapshot")), derivedCreate = server.requests.findIndex((x, index) => index > snapshotPost && x.method === "POST" && x.path === "/v4/sandboxes" && (x.body as { name: string }).name === derived), polls = server.requests.slice(snapshotPost + 1, derivedCreate).filter(x => x.method === "GET" && x.path === `/v2/sandboxes/${source}`)
    expect(polls).toHaveLength(3); expect(polls.every(x => x.query.includes("resume=false"))).toBe(true); expect(server.requests.slice(snapshotPost + 1, derivedCreate).some(x => x.path === `/v2/sandboxes/${source}` && x.query.includes("resume=true"))).toBe(false)
  })
  test("does not retry ambiguous create or command mutations and preserves cleanup errors", async () => {
    const create = fakeServer({ createFails: true }), artifacts = new Map<string, string>(); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(create.fetch), output: async (p, v) => { artifacts.set(p, v) } })).rejects.toThrow("probe failed"); expect(create.requests.filter(x => x.method === "POST" && x.path === "/v4/sandboxes")).toHaveLength(1)
    const command = fakeServer({ commandFault: "malformed", deleteSnapshotFails: true }); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(command.fetch), output: async () => {} })).rejects.toThrow("probe failed"); expect(command.requests.filter(x => x.method === "POST" && x.path.endsWith("/cmd"))).toHaveLength(1)
  })
  test("retries a timed-out terminal read without retrying command mutations", async () => { const server = fakeServer({ waitTimeouts: 1 }); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async () => {} })).resolves.toBeUndefined(); expect(server.requests.filter(x => x.method === "POST" && x.path.endsWith("/cmd"))).toHaveLength(8); expect(server.requests.filter(x => x.method === "GET" && /\/cmd\/[^/]+$/.test(x.path) && x.query === "teamId=team-private&wait=true")).toHaveLength(9) })
  test("reconciles only a transport-lost create response with an exact tagged non-resuming lookup", async () => {
    const recovered = fakeServer({ createFailsAfterCreate: true }); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(recovered.fetch), output: async () => {} })).resolves.toBeUndefined(); expect(recovered.requests.filter(x => x.method === "POST" && x.path === "/v4/sandboxes" && (x.body as { name: string }).name === source)).toHaveLength(1); expect(recovered.requests.some(x => x.path === `/v2/sandboxes/${source}` && x.query.includes("resume=false"))).toBe(true)
    for (const fault of [{ createFails: true }, { createFailsAfterCreate: true, mismatchedCreateTag: true }]) { const server = fakeServer(fault); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async () => {} })).rejects.toThrow("probe failed"); expect(server.requests.filter(x => x.method === "DELETE" && x.path.includes(source))).toHaveLength(0) }
  })
  test("continues cleanup after one snapshot delete failure", async () => { const server = fakeServer({ deleteSnapshotFails: true }); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async () => {} })).rejects.toThrow("probe failed"); expect(server.requests.filter(x => x.method === "DELETE" && x.path.startsWith("/v2/sandboxes/") && !x.path.includes("snapshots"))).toHaveLength(2); expect(server.requests.filter(x => x.method === "DELETE" && x.path.startsWith("/v2/sandboxes/snapshots/")).length).toBeGreaterThan(1) })
  test("deletes an owned sandbox when stop is rejected", async () => { const server = fakeServer({ stopFails: true }); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async () => {} })).rejects.toThrow("probe failed"); const deleted = server.requests.findIndex(x => x.method === "DELETE" && x.path === `/v2/sandboxes/${source}`); expect(deleted).toBeGreaterThan(-1); expect(server.requests.slice(deleted + 1).some(x => x.method === "GET" && x.path === `/v2/sandboxes/${source}`)).toBe(true) })
  test("rejects NDJSON overflow, stderr, structured errors, and nonzero command status", async () => { for (const commandFault of ["overflow", "stderr", "logError", "nonzero"] as const) { const server = fakeServer({ commandFault }); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async () => {} })).rejects.toThrow("probe failed"); expect(server.requests.filter(x => x.method === "POST" && x.path.endsWith("/cmd"))).toHaveLength(1) } })
  test("accepts deleted snapshot tombstones that remain GETtable and listed", async () => { const server = fakeServer({ deletedSnapshotsRemain: true }), artifacts = new Map<string, string>(); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async (p, v) => { artifacts.set(p, v) } })).resolves.toBeUndefined(); expect(server.requests.some(x => x.method === "GET" && x.path.startsWith("/v2/sandboxes/snapshots/snapshot-"))).toBe(true); expect(JSON.parse([...artifacts.entries()].find(([p]) => p.endsWith("sanitized.json"))![1]!).cleanup.exactBaseline).toBe(true) })
  test("does not delete an automatic snapshot tombstoned by keep-last before cleanup", async () => { const server = fakeServer({ evictAutomaticSnapshot: true }); await expect(runVercelSandboxCapabilityProbe(config, { ...deps(server.fetch), output: async () => {} })).resolves.toBeUndefined(); expect(server.requests.some(x => x.method === "GET" && x.path.endsWith(`/snapshots/snapshot-stop-${s1}`))).toBe(true); expect(server.requests.some(x => x.method === "DELETE" && x.path.endsWith(`/snapshots/snapshot-stop-${s1}`))).toBe(false) })
})

function deps(fetch: (input: string | URL | Request, init?: RequestInit) => Promise<Response>) { let now = 0; return { fetch, now: () => now++, sleep: async (_: number, signal: AbortSignal) => signal.throwIfAborted(), randomId: () => "01234567-89ab-cdef" } }
function fakeServer(fault: { createFails?: boolean; createFailsAfterCreate?: boolean; mismatchedCreateTag?: boolean; deleteSnapshotFails?: boolean; deletedSnapshotsRemain?: boolean; evictAutomaticSnapshot?: boolean; manualSnapshotStops?: boolean; snapshottingReads?: number; snapshotResponseStatus?: "pending" | "snapshotting" | "running"; stopFails?: boolean; waitTimeouts?: number; commandFault?: "malformed" | "overflow" | "stderr" | "logError" | "nonzero" } = {}) {
  const requests: Array<{ method: string; path: string; query: string; body: unknown; contentType: string | null; cwd: string | null }> = [], sandboxes = new Map<string, { session: string; status: string; tags: Record<string, string> }>([[baselineSandbox, { session: "baseline-session", status: "stopped", tags: { owner: "other" } }]]), snapshots = new Map<string, { sourceSessionId: string; status: "created" | "deleted" }>([[baselineSnapshot, { sourceSessionId: "baseline-session", status: "created" }]]); let commandCount = 0, longKilled = false, waitTimeouts = fault.waitTimeouts ?? 0, snapshottingReads = 0
  const fetch = async (input: string | URL | Request, init?: RequestInit): Promise<Response> => { const request = new Request(input, init), url = new URL(request.url), path = url.pathname, body = request.body && request.headers.get("content-type") === "application/json" ? await request.clone().json() : undefined; requests.push({ method: request.method, path, query: url.search.slice(1), body, contentType: request.headers.get("content-type"), cwd: request.headers.get("x-cwd") })
    if (request.method === "GET" && path === "/v2/sandboxes") { const final = url.searchParams.has("cursor"); return json({ sandboxes: final ? [...sandboxes].map(([name, x]) => ({ name, currentSessionId: x.session, status: x.status, tags: x.tags })) : [], pagination: { count: sandboxes.size, next: final ? null : "next-page" } }) }
    if (request.method === "GET" && path === "/v2/sandboxes/snapshots") { const final = url.searchParams.has("cursor"); return json({ snapshots: final ? [...snapshots].map(([id, item]) => ({ id, ...item })) : [], pagination: { count: snapshots.size, next: final ? null : "next-page" } }) }
    if (request.method === "POST" && path === "/v4/sandboxes") { if (fault.createFails) throw new TypeError("response lost"); const b = body as { name: string }; const session = b.name === source ? s1 : s4; sandboxes.set(b.name, { session, status: "running", tags: fault.mismatchedCreateTag ? { "waterbox-probe": "other" } : { "waterbox-probe": run } }); if (fault.createFailsAfterCreate) throw new TypeError("response lost"); return sandbox(b.name, session) }
    if (request.method === "GET" && path.startsWith("/v2/sandboxes/snapshots/")) { const item = snapshots.get(path.split("/").at(-1)!); return item ? json({ id: path.split("/").at(-1), ...item }) : json({}, 404) }
    if (request.method === "GET" && path.startsWith("/v2/sandboxes/") && !path.includes("/sessions/")) { const name = decodeURIComponent(path.split("/").at(-1)!), item = sandboxes.get(name); if (!item) return json({}, 404); if (url.searchParams.get("resume") === "true" && item.status === "stopped") { item.session = item.session === s1 ? s2 : s3; item.status = "running" } const status = item.status; if (name === source && status === "snapshotting" && snapshottingReads-- === 1) item.status = "running"; return sandbox(name, item.session, status, item.tags) }
    if (request.method === "POST" && path.endsWith("/fs/write")) return json({ ok: true })
    if (request.method === "POST" && path.endsWith("/cmd")) { const id = ++commandCount === 8 ? "cmd-long" : `cmd-${commandCount}`; return json({ command: commandResponse(id, path.split("/")[4]!, null) }) }
    if (request.method === "GET" && /\/cmd\/[^/]+$/.test(path)) { if (url.searchParams.get("wait") === "true" && waitTimeouts-- > 0) throw new DOMException("request timed out", "TimeoutError"); const id = path.split("/").at(-1)!; return json({ command: commandResponse(id, path.split("/")[4]!, id === "cmd-long" ? url.searchParams.get("wait") === "true" && longKilled ? 143 : null : fault.commandFault === "nonzero" ? 1 : 0) }) }
    if (request.method === "GET" && path.endsWith("/logs")) { if (fault.commandFault === "malformed") return ndjson("bad\n"); if (fault.commandFault === "overflow") return ndjson(`${JSON.stringify({ stream: "stdout", data: "x".repeat(65_537) })}\n`); if (fault.commandFault === "stderr") return ndjson(`${JSON.stringify({ stream: "stderr", data: "bad" })}\n`); if (fault.commandFault === "logError") return ndjson(`${JSON.stringify({ stream: "error", data: { code: "execution_failed", message: "private runner detail" } })}\n`); const id = path.split("/").at(-2); const data = id === "cmd-1" ? "v24.0.0\n" : id === "cmd-2" ? "/home/probe-default\n" : id === "cmd-4" ? "root\n" : ""; return ndjson(`${JSON.stringify({ stream: "stdout", data })}\n`) }
    if (request.method === "POST" && path.endsWith("/kill")) { longKilled = true; return json({ command: commandResponse(path.split("/").at(-2)!, path.split("/")[4]!, null) }) }
    if (request.method === "POST" && path.endsWith("/stop")) { if (fault.stopFails) return json({}, 415); const session = path.split("/")[4]!, item = [...sandboxes.values()].find(x => x.session === session)!; item.status = "stopped"; const id = `snapshot-stop-${session}`; snapshots.set(id, { sourceSessionId: session, status: "created" }); return json({ session: { id: session, status: "stopped" }, snapshot: { id, sourceSessionId: session, status: "created" } }) }
    if (request.method === "POST" && path === `/v3/sandboxes/sessions/${s2}/snapshot`) { snapshots.set(manual, { sourceSessionId: s2, status: "created" }); if (fault.manualSnapshotStops) sandboxes.get(source)!.status = "stopped"; else if (fault.snapshottingReads) { sandboxes.get(source)!.status = "snapshotting"; snapshottingReads = fault.snapshottingReads } if (fault.evictAutomaticSnapshot) snapshots.get(`snapshot-stop-${s1}`)!.status = "deleted"; return json({ session: { id: s2, status: fault.snapshotResponseStatus ?? "running" }, snapshot: { id: manual, sourceSessionId: s2, status: "created" } }, 201) }
    if (request.method === "DELETE" && path.startsWith("/v2/sandboxes/snapshots/")) { if (fault.deleteSnapshotFails) return json({}, 500); const id = path.split("/").at(-1)!, item = snapshots.get(id)!; if (fault.deletedSnapshotsRemain) { item.status = "deleted" } else snapshots.delete(id); return json({ snapshot: { id, ...item, status: "deleted" } }) }
    if (request.method === "DELETE" && path.startsWith("/v2/sandboxes/")) { sandboxes.delete(decodeURIComponent(path.split("/").at(-1)!)); return json({ ok: true }) }
    throw new Error(`unexpected ${request.method} ${path}`)
  }; return { fetch, requests }
}
function sandbox(name: string, session: string, status = "running", tags: Record<string, string> = { "waterbox-probe": run }) { return json({ sandbox: { name, currentSessionId: session, status, tags }, session: { id: session, projectId: config.projectId, cwd: "/home/probe-default", status: status === "stopped" ? "running" : status }, routes: [] }) }
function commandResponse(id: string, sessionId: string, exitCode: number | null) { return { id, sessionId, exitCode, name: "/bin/sh", args: ["-c", "true"], cwd: "/home/probe-default", startedAt: "2026-01-01T00:00:00.000Z" } }
function json(value: unknown, status = 200) { return Response.json(value, { status }) }
function ndjson(value: string) { return new Response(value, { headers: { "content-type": "application/x-ndjson" } }) }
